# Generated by Django 5.2.14 on 2026-09-04 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp'),
        ('organizations', '0007_plan_allows_attendance_plan_allows_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('HR', 'HR Manager / Company Admin'), ('SUB_ADMIN', 'Sub-Admin / Limited Access'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
        migrations.CreateModel(
            name='SubAdminPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_role_title', models.CharField(default='HR Manager', help_text='Display title e.g. HR Manager, Attendance Supervisor, Payroll Officer', max_length=120)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subadmin_permissions', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subadmin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub-Admin Permission',
                'verbose_name_plural': 'Sub-Admin Permissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
