# Generated by Django 5.2.14 on 2026-09-19 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_subadminpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTwoFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(db_index=True, default=False)),
                ('secret_key', models.CharField(blank=True, help_text='Base32 TOTP secret key unique to this user.', max_length=64)),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='List of dicts containing SHA-256 hashed one-time backup codes and used status.')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Two-Factor Configuration',
                'verbose_name_plural': 'User Two-Factor Configurations',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used', 'created_at'], name='accounts_tw_user_id_f60f8d_idx')],
            },
        ),
    ]
