import { v4 as uuid } from "uuid";
import {
  IconLayoutDashboard,
  IconUsers,
  IconCalendarEvent,
  IconBeach,
  IconCoin,
  IconLogout,
  IconUser,
  IconClock,
  IconCircleCheck,
  IconListDetails,
  IconFingerprint,
  IconChartBar,
  IconWallet,
  IconCalendarTime,
  IconSettings,
  IconBook,
  IconMessage,
  IconBuildingSkyscraper,
  IconShieldCheck,
  IconCreditCard,
  IconShieldLock,
} from "@tabler/icons-react";

//import custom type
import { MenuItemType } from "types/menuTypes";

export const DashboardMenu: MenuItemType[] = [
  {
    id: uuid(),
    title: "Admin Dashboard",
    link: "/dashboard",
    moduleKey: "dashboard",
    icon: <IconLayoutDashboard size={20} strokeWidth={1.5} />,
  },
  {
    id: uuid(),
    title: "HR MANAGEMENT",
    grouptitle: true,
  },
  {
    id: uuid(),
    title: "Employees",
    link: "/employees",
    moduleKey: "employees",
    featureKey: "allows_employees",
    icon: <IconUsers size={20} strokeWidth={1.5} />,
  },
  {
    id: uuid(),
    title: "Attendance",
    moduleKey: "attendance",
    featureKey: "allows_attendance",
    icon: <IconCalendarEvent size={20} strokeWidth={1.5} />,
    children: [
      {
        id: uuid(),
        title: "Today's Attendance",
        link: "/attendance/todays-attendance",
        moduleKey: "attendance",
        featureKey: "allows_attendance",
        icon: <IconCircleCheck size={20} strokeWidth={1.5} />,
      },
      {
        id: uuid(),
        title: "Attendance Records",
        link: "/attendance/records",
        moduleKey: "attendance",
        featureKey: "allows_attendance",
        icon: <IconListDetails size={20} strokeWidth={1.5} />,
      },
    ],
  },
  {
    id: uuid(),
    title: "Projects & Tasks",
    link: "/tasks",
    moduleKey: "tasks",
    featureKey: "allows_projects_tasks",
    requiresPro: true,
    icon: <IconListDetails size={20} strokeWidth={1.5} />,
  },
  {
    id: uuid(),
    title: "Chat & Messages",
    link: "/chat",
    moduleKey: "chat",
    featureKey: "allows_chat",
    requiresPro: true,
    icon: <IconMessage size={20} strokeWidth={1.5} />,
    badge: "Beta",
    badgecolor: "primary",
  },
  {
    id: uuid(),
    title: "Holidays",
    link: "/holidays",
    moduleKey: "holidays",
    featureKey: "allows_holidays",
    icon: <IconBeach size={20} strokeWidth={1.5} />,
  },
  {
    id: uuid(),
    title: "Salary & Payroll",
    link: "/salary",
    moduleKey: "payroll",
    featureKey: "allows_payroll_reports",
    requiresPro: true,
    icon: <IconCoin size={20} strokeWidth={1.5} />,
  },
  {
    id: uuid(),
    title: "Leave Requests",
    link: "/leaves",
    moduleKey: "leaves",
    featureKey: "allows_leaves",
    icon: <IconCalendarTime size={20} strokeWidth={1.5} />,
  },
  {
    id: uuid(),
    title: "SYSTEM",
    grouptitle: true,
  },
  {
    id: uuid(),
    title: "Plans & Billing",
    link: "/plans",
    adminOnly: true,
    icon: <IconCreditCard size={20} strokeWidth={1.5} />,
  },
  {
    id: uuid(),
    title: "Settings",
    link: "/settings",
    moduleKey: "settings",
    icon: <IconSettings size={20} strokeWidth={1.5} />,
  },
  {
    id: uuid(),
    title: "Rulebook",
    link: "/system/rulebook",
    featureKey: "allows_custom_shifts",
    requiresPro: true,
    icon: <IconBook size={20} strokeWidth={1.5} />,
  },
  {
    id: uuid(),
    title: "Logout",
    link: "/sign-in",
    icon: <IconLogout size={20} strokeWidth={1.5} />,
    logout: true,
  },
];