import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";

import ClientWrapper from "components/common/ClientWrapper";

import "@tabler/icons-webfont/dist/tabler-icons.min.css";
import "simplebar-react/dist/simplebar.min.css";
import "swiper/swiper-bundle.css";
import "styles/theme.scss";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AttendStack",
  description: "Generated by AttendStack",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientWrapper>
      <html lang="en" className="expanded" data-scroll-behavior="smooth">
        <body className={`${publicSans.variable}`}>
          {children}
          <ToastContainer />
        </body>
      </html>
    </ClientWrapper>
  );
}