# Generated by Django 5.2.14 on 2026-08-12 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='acknowledged_by',
            field=models.ManyToManyField(blank=True, related_name='acknowledged_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='department_target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_announcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='requires_acknowledgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='target_type',
            field=models.CharField(default='EVERYONE', max_length=20),
        ),
    ]
