# Generated by Django 5.2.14 on 2026-08-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_reply_to_alter_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('FILE', 'File'), ('SYSTEM', 'System')], default='TEXT', max_length=10),
        ),
    ]
