# Generated by Django 5.2.8 on 2026-08-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_owner_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='external_company_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='external_source',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
