# Generated by Django 5.2.14 on 2026-08-19 08:56

import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_api_key_organization_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_employees',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan_source',
            field=models.CharField(blank=True, default='ATTENDSTACK_DIRECT', max_length=40),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRING_SOON', 'Expiring Soon'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='api_key',
            field=models.CharField(blank=True, db_index=True, default=organizations.models.generate_api_key, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan_name',
            field=models.CharField(blank=True, default='Standard Plan', max_length=100, null=True),
        ),
    ]
