# Generated by Django 5.2.14 on 2026-08-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_max_employees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_employees', models.IntegerField(default=50, help_text='-1 for unlimited')),
                ('badge_text', models.CharField(blank=True, default='', max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('allows_geofencing', models.BooleanField(default=False, help_text='Office IP Shield & GPS Geofencing')),
                ('allows_payroll_reports', models.BooleanField(default=False, help_text='Automated Payroll & Overtime Reports')),
                ('allows_auto_checkout', models.BooleanField(default=False, help_text='Auto-checkout & Shift Rules')),
                ('allows_custom_shifts', models.BooleanField(default=False, help_text='Multi-shift & Late Cutoff Rules')),
                ('allows_dedicated_api', models.BooleanField(default=False, help_text='Dedicated API Key & Webhooks')),
                ('allows_simplyjob_sync', models.BooleanField(default=True, help_text='SimplyJob Candidate Onboarding Sync')),
                ('features_list', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
    ]
