# Generated by Django 5.2.14 on 2026-08-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='allows_attendance',
            field=models.BooleanField(default=True, help_text='Daily Attendance & Live Punches'),
        ),
        migrations.AddField(
            model_name='plan',
            name='allows_chat',
            field=models.BooleanField(default=False, help_text='Team Chat & Direct Messaging (Beta)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='allows_employees',
            field=models.BooleanField(default=True, help_text='Employees Directory & Profiles'),
        ),
        migrations.AddField(
            model_name='plan',
            name='allows_holidays',
            field=models.BooleanField(default=True, help_text='Holiday Calendar Management'),
        ),
        migrations.AddField(
            model_name='plan',
            name='allows_leaves',
            field=models.BooleanField(default=True, help_text='Leave Requests & Approval Workflow'),
        ),
        migrations.AddField(
            model_name='plan',
            name='allows_projects_tasks',
            field=models.BooleanField(default=False, help_text='Projects & Tasks Workspace'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='allows_auto_checkout',
            field=models.BooleanField(default=False, help_text='Auto-Checkout & Shift Logic'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='allows_custom_shifts',
            field=models.BooleanField(default=False, help_text='Multi-Shift & Late Rulebooks'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='allows_payroll_reports',
            field=models.BooleanField(default=False, help_text='Salary & Payroll Processing'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='allows_simplyjob_sync',
            field=models.BooleanField(default=True, help_text='SimplyJob Candidate Sync Engine'),
        ),
    ]
