# Generated by Django 5.2.8 on 2026-06-18 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_restore_employee_login_access'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tasks/attachments/'),
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='task',
            name='project_category',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['department', 'project_category'], name='tasks_task_departm_dc0b2a_idx'),
        ),
    ]
