# Generated by Django 5.2.8 on 2026-06-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_attachment_task_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='employee_attachment',
            field=models.FileField(blank=True, null=True, upload_to='tasks/employee-attachments/'),
        ),
    ]
