# Generated by Django 5.2.8 on 2026-06-18 09:55

from django.db import migrations, models


def move_blocked_tasks_to_on_hold(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    Task.objects.filter(status="BLOCKED").update(status="ON_HOLD")


def move_on_hold_tasks_to_blocked(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    Task.objects.filter(status="ON_HOLD").update(status="BLOCKED")


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_employee_attachment'),
    ]

    operations = [
        migrations.RunPython(move_blocked_tasks_to_on_hold, move_on_hold_tasks_to_blocked),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
