# Generated by Django 5.2.8 on 2026-06-19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("employees", "0001_initial"),
        ("tasks", "0004_alter_task_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("key", models.CharField(db_index=True, max_length=12)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("PLANNING", "Planning"), ("ACTIVE", "Active"), ("ON_HOLD", "On Hold"), ("COMPLETED", "Completed"), ("ARCHIVED", "Archived")], db_index=True, default="ACTIVE", max_length=20)),
                ("department", models.CharField(blank=True, db_index=True, max_length=120)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                ("color", models.CharField(default="#4f46e5", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_projects", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="projects", to="organizations.organization")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="owned_projects", to="employees.employee")),
            ],
            options={"ordering": ["status", "due_date", "name"]},
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(fields=("organization", "key"), name="unique_project_key_per_organization"),
        ),
        migrations.AddIndex(model_name="project", index=models.Index(fields=["organization", "status"], name="tasks_proje_organiz_52817a_idx")),
        migrations.AddIndex(model_name="project", index=models.Index(fields=["owner", "status"], name="tasks_proje_owner_i_6e4384_idx")),
        migrations.AddField(model_name="task", name="parent", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="subtasks", to="tasks.task")),
        migrations.AddField(model_name="task", name="project", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="tasks.project")),
        migrations.AddField(model_name="task", name="position", field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name="task", name="start_date", field=models.DateField(blank=True, null=True)),
        migrations.AddIndex(model_name="task", index=models.Index(fields=["project", "parent", "status"], name="tasks_task_project_da7808_idx")),
    ]
