# Generated by Django 5.2.8 on 2026-06-20

from django.db import migrations, models


def copy_primary_assignees(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    for task in Task.objects.exclude(assignee__isnull=True).iterator():
        task.assignees.add(task.assignee_id)


def remove_copied_assignees(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    through = Task.assignees.through
    through.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_project_task_hierarchy"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(blank=True, help_text="All employees responsible for this task. The primary assignee is retained for legacy workflows.", related_name="collaborative_tasks", to="employees.employee"),
        ),
        migrations.RunPython(copy_primary_assignees, remove_copied_assignees),
    ]
