# Generated by Django 5.2.14 on 2026-05-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='sunday_unpaid_rule_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, Sunday is marked as unpaid when employee is on leave/absent on the day before or after Sunday'),
        ),
    ]
