# Generated by Django 5.2.14 on 2026-05-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_systemsettings_sunday_unpaid_rule_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='annual_paid_leave_days',
            field=models.IntegerField(default=21, help_text='Default number of annual paid leave days per employee'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='casual_leave_days',
            field=models.IntegerField(default=6, help_text='Default number of annual casual leave days per employee'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='maternity_leave_days',
            field=models.IntegerField(default=180, help_text='Default number of maternity leave days per employee'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='paternity_leave_days',
            field=models.IntegerField(default=14, help_text='Default number of paternity leave days per employee'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sick_leave_days',
            field=models.IntegerField(default=12, help_text='Default number of annual sick leave days per employee'),
        ),
    ]
