# Generated by Django 5.2.14 on 2026-05-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_systemsettings_annual_paid_leave_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='burger_rule_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, a holiday is marked as unpaid if it is sandwiched between two leave days.'),
        ),
    ]
