# Generated by Codex on 2026-05-30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_systemsettings_burger_rule_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="monthly_paid_leave_days",
            field=models.IntegerField(
                default=1,
                help_text="Number of approved leave days per employee that are paid each month",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
    ]
