# Generated by Django 5.2.14 on 2026-05-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_systemsettings_monthly_paid_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='attendance_rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
