# Generated by Django 5.2.14 on 2026-06-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_systemsettings_attendance_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
