# Generated by Django 5.2.14 on 2026-06-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_systemsettings_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='geofence_radius',
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='office_latitude',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='Office latitude for geofencing.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='office_longitude',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='Office longitude for geofencing.', max_digits=12, null=True),
        ),
    ]
