# Generated by Django 5.2.14 on 2026-06-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_remove_systemsettings_geofence_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='geofence_radius',
            field=models.PositiveIntegerField(default=100, help_text='Allowed geofencing radius in meters.'),
        ),
    ]
