# Generated by Codex on 2026-06-06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0009_systemsettings_geofence_radius"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="leave_carryover_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Carry unused monthly paid leave balance into later months in the same calendar year",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="max_carryover_days",
            field=models.IntegerField(
                default=5,
                help_text="Maximum unused paid leave days that can be carried forward",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(365),
                ],
            ),
        ),
    ]
