# Generated by Codex on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0010_systemsettings_leave_carryover"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="company_size",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="company_website",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="industry",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="registration_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="tax_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
