# Generated by Codex on 2026-06-24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0011_systemsettings_company_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="bereavement_leave_days",
            field=models.PositiveIntegerField(
                default=5,
                validators=[django.core.validators.MaxValueValidator(365)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="marriage_leave_days",
            field=models.PositiveIntegerField(
                default=10,
                validators=[django.core.validators.MaxValueValidator(365)],
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="casual_leave_days",
            field=models.PositiveIntegerField(
                default=6,
                validators=[django.core.validators.MaxValueValidator(365)],
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="sick_leave_days",
            field=models.PositiveIntegerField(
                default=12,
                validators=[django.core.validators.MaxValueValidator(365)],
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="maternity_leave_days",
            field=models.PositiveIntegerField(
                default=180,
                validators=[django.core.validators.MaxValueValidator(365)],
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="paternity_leave_days",
            field=models.PositiveIntegerField(
                default=14,
                validators=[django.core.validators.MaxValueValidator(365)],
            ),
        ),
        migrations.RemoveField(model_name="systemsettings", name="annual_paid_leave_days"),
        migrations.RemoveField(model_name="systemsettings", name="monthly_paid_leave_days"),
        migrations.RemoveField(model_name="systemsettings", name="leave_carryover_enabled"),
        migrations.RemoveField(model_name="systemsettings", name="max_carryover_days"),
        migrations.RemoveField(model_name="systemsettings", name="half_day_threshold"),
    ]
