# Generated by Codex on 2026-06-30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0012_replace_monthly_paid_leave_with_type_allocations"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="casual_leave_monthly_limit",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Maximum Casual Leave days an employee may request in one calendar month.",
                validators=[django.core.validators.MaxValueValidator(31)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="sick_leave_monthly_limit",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Maximum Sick Leave days an employee may request in one calendar month.",
                validators=[django.core.validators.MaxValueValidator(31)],
            ),
        ),
    ]
