# Generated by Django 5.2.14 on 2026-08-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_systemsettings_monthly_leave_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_increment_months',
            field=models.PositiveIntegerField(default=12, help_text='Default increment cycle interval in months (e.g. 1, 3, 6, 9, 12, 18, 24).'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_increment_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT_AMOUNT', 'Flat Amount (Rupees)')], default='PERCENTAGE', help_text='Default increment calculation method.', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_increment_value',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Default increment value (percentage or rupee amount).', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='increment_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic calculation and scheduling of employee salary increments.'),
        ),
    ]
