# Generated by Django 5.2.14 on 2026-09-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_systemsettings_default_increment_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='company_bank_account_no',
            field=models.CharField(blank=True, default='', help_text='Company bank account number.', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_bank_branch',
            field=models.CharField(blank=True, default='', help_text='Company bank branch name.', max_length=150),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_bank_ifsc',
            field=models.CharField(blank=True, default='', help_text='Company bank IFSC code.', max_length=30),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_bank_name',
            field=models.CharField(blank=True, default='', help_text='Company primary bank name.', max_length=150),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_upi_id',
            field=models.CharField(blank=True, default='', help_text='Company UPI ID for payments.', max_length=100),
        ),
    ]
