# Generated by Django 5.2.14 on 2026-09-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_systemsettings_company_bank_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='early_checkout_grace_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Minutes before shift end allowed without early checkout penalty.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='early_checkout_penalty',
            field=models.CharField(choices=[('HALF_DAY', 'Half Day'), ('PRO_RATED', 'Pro-rated Hourly Deduction'), ('NONE', 'No Penalty')], default='HALF_DAY', help_text='Policy for early checkout before grace period.', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='min_hours_full_day',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Minimum working hours required for full-day.', max_digits=4),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='min_hours_half_day',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Minimum working hours required for half-day.', max_digits=4),
        ),
    ]
