# Generated by Django 5.2.8 on 2026-05-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(unique=True)),
                ('type', models.CharField(choices=[('Public Holiday', 'Public Holiday'), ('National Holiday', 'National Holiday'), ('Festival', 'Festival'), ('Optional Holiday', 'Optional Holiday')], default='Public Holiday', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
