# Generated by Django 5.2.14 on 2026-06-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_auto_20260604_1608'),
    ]

    operations = [
    ]
