# Generated by Django 6.0.5 on 2026-05-15 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late Entry'), ('HALF_DAY', 'Half-day'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'On Leave')], db_index=True, default='PRESENT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-date', 'employee__full_name'],
                'indexes': [models.Index(fields=['date', 'status'], name='attendance__date_64c311_idx'), models.Index(fields=['employee', 'date'], name='attendance__employe_b6a945_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_attendance_date')],
            },
        ),
    ]
