# Generated by Django 5.2.14 on 2026-05-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_clean_attendance_status_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late Entry'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave'), ('PAID_LEAVE', 'Paid Leave'), ('HOLIDAY', 'Holiday'), ('SUNDAY_PAID', 'Sunday'), ('SUNDAY_UNPAID', 'Sunday Unpaid')], db_index=True, default='PRESENT', max_length=20),
        ),
    ]
