# Generated by Django 5.2.14 on 2026-05-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Whether this day is paid in payroll'),
        ),
    ]
