# Generated by Django 5.2.14 on 2026-05-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancerecord_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('ANNUAL', 'Annual Leave'), ('STUDY', 'Study Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('BEREAVEMENT', 'Bereavement Leave'), ('MARRIAGE', 'Marriage Leave'), ('OTHER', 'Other')], default='CASUAL', max_length=20),
        ),
    ]
