# Generated by Codex on 2026-05-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_alter_leaverequest_leave_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="leave_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave request that created this attendance entry, when applicable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="attendance.leaverequest",
            ),
        ),
    ]
