# Generated by Django 5.2.14 on 2026-06-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendancerecord_leave_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address used when employee checked in', null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude at the time of check-in', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude at the time of check-in', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address used when employee checked out', null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude at the time of check-out', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude at the time of check-out', max_digits=9, null=True),
        ),
    ]
