# Generated by Codex on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_add_audit_trail_to_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="is_half_day",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is a half-day Casual or Sick leave request.",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("CASUAL", "Casual Leave"),
                    ("SICK", "Sick Leave"),
                    ("MATERNITY", "Maternity Leave"),
                    ("PATERNITY", "Paternity Leave"),
                    ("BEREAVEMENT", "Bereavement Leave"),
                    ("MARRIAGE", "Marriage Leave"),
                ],
                default="CASUAL",
                max_length=20,
            ),
        ),
    ]
