# Generated by Codex on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_half_day_leave_requests_and_supported_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Supporting document supplied with the leave request.",
                null=True,
                upload_to="leave_attachments/%Y/%m/",
            ),
        ),
    ]
