# Generated by Django 5.2.14 on 2026-09-16 07:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_leaverequest_attachment'),
        ('organizations', '0007_plan_allows_attendance_plan_allows_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='early_departure_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Shortfall minutes if employee checked out before shift completion grace period.'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. General Shift, Morning Shift, Night Shift', max_length=100)),
                ('code', models.CharField(blank=True, help_text='e.g. GEN, MORN, NIGHT', max_length=30)),
                ('start_time', models.TimeField(default='10:00:00')),
                ('end_time', models.TimeField(default='18:00:00')),
                ('late_grace_minutes', models.PositiveIntegerField(default=15, help_text='Grace period in minutes after shift start before marked late.')),
                ('early_checkout_grace_minutes', models.PositiveIntegerField(default=15, help_text='Minutes before shift end allowed without early checkout penalty.')),
                ('early_checkout_penalty', models.CharField(choices=[('HALF_DAY', 'Half Day'), ('PRO_RATED', 'Pro-Rated Salary Deduction'), ('NONE', 'No Penalty')], default='HALF_DAY', help_text='Policy applied when employee checks out before early checkout grace period.', max_length=20)),
                ('min_hours_half_day', models.DecimalField(decimal_places=2, default=4.0, help_text='Minimum working hours required for half day credit.', max_digits=4)),
                ('min_hours_full_day', models.DecimalField(decimal_places=2, default=8.0, help_text='Minimum working hours required for full day credit.', max_digits=4)),
                ('is_default', models.BooleanField(default=False, help_text='Designates this shift as the default for employees with no shift assigned.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Shift assigned for this attendance day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='attendance.shift'),
        ),
    ]
