# Generated by Django 5.2.14 on 2026-05-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='deduction_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
