# Generated by Django 5.2.14 on 2026-08-11 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_employee_custom_increment_months_and_more'),
        ('payroll', '0002_payroll_deduction_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeIncrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(db_index=True)),
                ('current_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('increment_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT_AMOUNT', 'Flat Amount')], default='PERCENTAGE', max_length=20)),
                ('increment_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('calculated_increment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('new_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='PENDING', max_length=20)),
                ('rescheduled_date', models.DateField(blank=True, null=True)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_increments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increments', to='employees.employee')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='payroll_emp_status_6c39e3_idx')],
            },
        ),
    ]
