# Generated by Django 5.2.14 on 2026-09-05 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employeeincrement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='is_modified_after_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='modification_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payroll',
            name='modification_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payroll',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_payrolls', to=settings.AUTH_USER_MODEL),
        ),
    ]
