# Generated by Django 5.2.14 on 2026-09-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payroll_is_modified_after_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeincrement',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='True if this increment has custom raise amount/type overridden from company default.'),
        ),
    ]
