export type CurrentEmployee = {
  id: string;
  employee_id: string;
  full_name: string;
  email: string;
  phone: string;
  date_of_birth: string | null;
  aadhaar_number: string;
  address: string;
  profile_photo_url: string | null;
  aadhaar_document_url: string | null;
  pan_card_document_url: string | null;
  cv_document_url: string | null;
  account_exists: boolean;
  emergency_contact_name: string;
  emergency_contact_relationship: string;
  emergency_contact_phone: string;
  joining_date: string;
  department: string;
  designation: string;
  employment_type: string;
  employment_type_label: string;
  reporting_manager: string;
  status: "ACTIVE" | "PROVISION" | "ON_LEAVE" | "NOTICE_PERIOD" | "INACTIVE" | "TERMINATED";
  status_label: string;
  status_end_date?: string | null;
  auto_transition_status?: string | null;
  auto_transition_status_label?: string | null;
  annual_salary: string;
  pay_frequency: string;
  pay_frequency_label: string;
  bank_name: string;
  bank_account_number: string;
  ifsc_code: string;
  tax_id: string;
  created_at: string;
  updated_at: string;
};
