# Generated by Django 6.0.5 on 2026-05-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, unique=True),
        ),
    ]
