# Generated by Django 5.2.14 on 2026-05-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_annual_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='annual_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
