# Generated by Codex on 2026-06-22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_employee_self_registration_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="ifsc_code",
            field=models.CharField(
                blank=True,
                max_length=11,
                validators=[django.core.validators.RegexValidator("^$|^[A-Z]{4}0[A-Z0-9]{6}$", "Enter a valid 11-character IFSC code.")],
            ),
        ),
    ]
