# Generated by Codex on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0008_employee_ifsc_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="cv_document",
            field=models.FileField(blank=True, null=True, upload_to="employees/cv/"),
        ),
        migrations.AddField(
            model_name="employee",
            name="pan_card_document",
            field=models.FileField(blank=True, null=True, upload_to="employees/pan/"),
        ),
    ]
