# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0009_employee_profile_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PROVISION", "Provision"),
                    ("INACTIVE", "Inactive"),
                    ("ON_LEAVE", "On Leave"),
                    ("TERMINATED", "Terminated"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
