# Generated by Django 5.2.8 on 2026-08-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_leave_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='external_application_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='external_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='employee',
            name='external_source',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
