# Generated by Django 5.2.14 on 2026-08-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_external_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='custom_increment_months',
            field=models.PositiveIntegerField(blank=True, help_text='Custom increment cycle interval in months.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='custom_increment_type',
            field=models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('FLAT_AMOUNT', 'Flat Amount (Rupees)')], help_text='Custom calculation method for employee increment.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='custom_increment_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom increment value (percentage or rupee amount).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='increment_status',
            field=models.CharField(choices=[('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='ENABLED', help_text='Controls if increment processing is active for this employee.', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_increment_date',
            field=models.DateField(blank=True, help_text='Date of last approved increment.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_increment_date',
            field=models.DateField(blank=True, help_text='Next expected due date for increment.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='override_increment_policy',
            field=models.BooleanField(default=False, help_text='If checked, this employee uses custom increment settings instead of company defaults.'),
        ),
    ]
