# Generated by Django 5.2.14 on 2026-09-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_add_status_end_date_and_auto_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='esic_number',
            field=models.CharField(blank=True, help_text='ESIC Insurance Number', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_number',
            field=models.CharField(blank=True, help_text='Permanent Account Number (PAN)', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_number',
            field=models.CharField(blank=True, help_text='Provident Fund (PF) Account Number', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='uan_number',
            field=models.CharField(blank=True, help_text='Universal Account Number (UAN)', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeestatushistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
