# Generated by Django 5.2.14 on 2026-08-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_add_status_end_date_and_auto_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeestatushistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
