# Generated by Django 5.2.14 on 2026-09-16 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendancerecord_early_departure_minutes_shift_and_more'),
        ('employees', '0018_employee_esic_number_employee_pan_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Assigned shift for this employee. Blank defaults to company default shift.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='attendance.shift'),
        ),
    ]
