# Generated by Django 5.2.14 on 2026-09-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_employeestatushistory_end_date'),
        ('employees', '0018_employee_esic_number_employee_pan_number_and_more'),
    ]

    operations = [
    ]
